'use client';
import Link from 'next/link';
import {useState,useEffect} from 'react';
import {usePathname} from 'next/navigation';
export function Navigation(){const [open,setOpen]=useState(false);const path=usePathname();useEffect(()=>setOpen(false),[path]);useEffect(()=>{const close=e=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);return <nav className={'navigation '+(open?'expanded':'')}><Link href="/" aria-label="Mali Roshanshah home"><img className="logo" src="/assets/ef9234f6d485d531.png" alt="MR"/></Link><button className="menu-toggle" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} aria-controls="nav-links" onClick={()=>setOpen(!open)}>{open?'×':'☰'}</button><div id="nav-links" className="nav-links"><Link href="/">Home</Link><Link href="/projects">Projects</Link><Link href="/about">About</Link><Link href="/contact" className="pill">Contact Me</Link></div></nav>}
const socials=[['GitHub','https://github.com/Malishaah','95729b5f4d52683d'],['LinkedIn','https://www.linkedin.com/in/maliroshanshah/','c0f48e505cd50c16'],['Email','mailto:malirnsh@gmail.com','2209047a4f2a18e9'],['Pinterest','https://pin.it/5Sv96TlPE','6083f9a34adc1726']];
export function Socials(){return <div className="socials">{socials.map(([name,url,icon])=><a key={name} href={url} aria-label={name}><img src={'/assets/'+icon+'.svg'} alt=""/></a>)}</div>}
export function Gems(){return <div className="gems" aria-hidden="true">{[0,1,2,3].map(i=><img key={i} className={'gem gem-'+i} src="/assets/389459748d7af5e0.png" alt=""/>)}</div>}
export function ProjectGrid({projects}){const [all,setAll]=useState(false);return <><div className="project-grid">{projects.slice(0,all?7:4).map(p=><Link href={'/project-details/'+p.slug} className="project-card" key={p.slug}><img src={p.blocks.find(b=>b.type==='image')?.src} alt={p.title}/><h2>{p.title}</h2><p>{p.description}</p><span>{p.slug==='its-learning'||p.slug==='trackoon-privacy-tool'?'2026':p.slug==='exploid-game'?'2024':'2025'}</span></Link>)}</div>{!all&&<button className="pill load-more" onClick={()=>setAll(true)}>Load More</button>}</>}
