'use client';
import {useEffect,useRef} from 'react';
import fragment from './shader';
export default function Background(){const ref=useRef(null);useEffect(()=>{const canvas=ref.current;const gl=canvas.getContext('webgl2',{alpha:false,antialias:false});if(!gl)return;let raf=0;const compile=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){console.error(gl.getShaderInfoLog(s));gl.deleteShader(s);return null}return s};const vs=compile(gl.VERTEX_SHADER,`#version 300 es
in vec2 position;out vec2 v_uv;void main(){v_uv=position*.5+.5;gl_Position=vec4(position,0.,1.);}`);const names={contrast:1.2,distBias:0,dither:.05,ditherMode:0,exposure:1,jellify:0,loop:0,saturation:1,scale:1.1,seed:40,speed:.1,turbAmp:.5,turbFreq:.2,turbIter:7,waveFreq:2};const fs=compile(gl.FRAGMENT_SHADER,`#version 300 es
precision highp float;precision highp int;
in vec2 v_uv;out vec4 fragColor;uniform vec2 u_resolution;uniform float u_time,u_pixelRatio;uniform vec4 u_colors[8];uniform int u_colors_length;
${Object.keys(names).map(n=>'uniform float u_'+n+';').join('\n')}
${fragment}`);if(!vs||!fs)return;const program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))return;gl.useProgram(program);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const pos=gl.getAttribLocation(program,'position');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);const u=n=>gl.getUniformLocation(program,'u_'+n);Object.entries(names).forEach(([n,v])=>gl.uniform1f(u(n),v));gl.uniform1i(u('colors_length'),3);gl.uniform4fv(u('colors[0]'),new Float32Array([228/255,219/255,211/255,1,193/255,176/255,167/255,1,101/255,67/255,45/255,1]));gl.uniform1f(u('pixelRatio'),1);const time=u('time'),res=u('resolution');const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;const start=performance.now();function draw(now){const w=Math.round(innerWidth*.75),h=Math.round(innerHeight*.75);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}gl.uniform2f(res,w,h);gl.uniform1f(time,reduce?0:(now-start)/1000);gl.drawArrays(gl.TRIANGLES,0,6);if(!reduce)raf=requestAnimationFrame(draw)}raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);gl.deleteBuffer(b);gl.deleteProgram(program);gl.deleteShader(vs);gl.deleteShader(fs)}},[]);return <canvas className="background" ref={ref} aria-hidden="true"/>}
