export const projectInfo = {
  'its-learning': { name: 'Itslearning', subtitle: 'Making essential student tasks easier to find.', category: 'UX & UI', tags: ['UX research', 'Mobile app', 'Usability testing'], color: 'peach', year: '2026', summary: 'A team redesign informed by usability tests with five students, focused on navigation, information architecture and grade visibility.' },
  'trackoon-privacy-tool': { name: 'Trackoon', subtitle: 'Turning privacy details into decisions people understand.', category: 'UX & UI', tags: ['UX research', 'Interaction design', 'Privacy'], color: 'lilac', year: '2026', summary: 'An academic group project that combined interviews, workshop insights and user testing in a browser-based privacy tool.' },
  'movekind': { name: 'MoveKind', subtitle: 'Accessible movement and rehabilitation, in one place.', category: 'Design & code', tags: ['Accessibility', 'UX/UI', 'Frontend'], color: 'sage', year: '2025', summary: 'I designed and built accessibility-first exercise flows using Next.js and a headless CMS.' },
  'västtrafik-app': { name: 'Västtrafik', subtitle: 'A clearer route from planning to ticket purchase.', category: 'UX & UI', tags: ['User research', 'Mobile app', 'Prototyping'], color: 'blue', year: '2025', summary: 'A collaborative redesign shaped by surveys, interviews and iterative usability testing.' },
  'bee-rise-game': { name: 'Bee Rise', subtitle: 'A playful browser game shaped by motion and timing.', category: 'Design & code', tags: ['Game design', 'Animation', 'TypeScript'], color: 'yellow', year: '2025', summary: 'I led the visual direction and implemented the interface, animations and parts of the game logic in TypeScript.' },
  'bloom-ecommerce-plants': { name: 'Bloom', subtitle: 'A simpler way to find and buy the right plant.', category: 'Design & code', tags: ['E-commerce', 'UX/UI', 'Frontend'], color: 'sage', year: '2025', summary: 'I designed the core shopping journey and contributed to the frontend implementation, including product management tools.' },
  'exploid-game': { name: 'Healthcare UX', subtitle: 'Making healthcare products easier to find and understand.', category: 'UX & UI', tags: ['Accessibility', 'Research', 'Redesign'], color: 'peach', year: '2024', summary: 'I led the accessibility analysis and most of the final UI, improving contrast, navigation and content hierarchy.' },
};
